language: scala

jdk:
  - oraclejdk8

script:
   - sbt test-plugin

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2/cache/ch.jodersky -depth -name "sbt-jni*" -exec rm -r {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
